version: '3'

services:

  app:
    image: youta-python
    ports:
      - 5000:5000


  apache:
    image: httpd:2.4.43-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./scripts/httpd.conf:/usr/local/apache2/conf/httpd.conf


  #  youta-web:
  #    image: youta-web
  #    ports:
  #      - 3000:3000
  #    depends_on:
  #      - youta-python
  #    stdin_open: true

#      - ./scripts/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
#      - ./scripts/ck.crt:/usr/local/apache2/conf/ck.crt
#      - ./scripts/ck.key:/usr/local/apache2/conf/ck.key
#      - ./scripts/d-QN5eGOavA_pp2_WrsDoutpRtKcnEUZSRXolPpPQGA:/usr/local/apache2/htdocs/.well-known/acme-challenge/d-QN5eGOavA_pp2_WrsDoutpRtKcnEUZSRXolPpPQGA
#
